const express=require("express");
const r=express.Router();
const {register,login,forgotpwd,profile,uploadpost,getallposts,addLikes,removeLikes, storelikedetails, checklike,getpost, sendfriendreq,checkfriendreq,delfriendreq, editdetails, editpic, getallusers, getfriendreq, acceptreq, friends, unfriend, sentmsg, getmsg, postcomment, allcomments, share, deletepic}=require("../controller/controll");
const upload=require("../middleware/profile");
const check=require("../middleware/register");
const posted=require("../middleware/post");
r.route("/register").post(upload,check(),register);
r.route("/login").post(login);
r.route("/forgotpassword").patch(forgotpwd);
r.route("/profile").get(profile);
r.route("/uploadpost").post(posted,uploadpost);
r.route("/getallposts").get(getallposts);
r.route("/addlikes").patch(addLikes);
r.route("/removelikes").patch(removeLikes);
r.route("/storelikedetails").post(storelikedetails);
r.route("/checklike").post(checklike);
r.route("/getpost").get(getpost);
r.route("/sendfriendrequest").post(sendfriendreq);
r.route("/checkfriendrequest").post(checkfriendreq);
r.route("/deletefriendrequest").delete(delfriendreq);
r.route("/editdetails").patch(editdetails);
r.route("/editpic").patch(upload,editpic);
r.route("/getallusers").get(getallusers);
r.route("/getfriendrequests").get(getfriendreq);
r.route("/acceptfriendrequest").post(acceptreq);
r.route("/friends").get(friends);
r.route("/unfriend").delete(unfriend);
r.route("/sentmessage").post(sentmsg);
r.route("/getmessage/:email").get(getmsg);
r.route("/postcomment").post(postcomment);
r.route("/allcomments/:id").get(allcomments);
r.route("/sharepost").post(share);
r.route("/deletepost").delete(deletepic);
module.exports=r;